#!/bin/bash
HERE=$(cd "$(dirname "$BASH_SOURCE")"; cd -P "$(dirname "$(readlink "$BASH_SOURCE" || echo .)")"; pwd)

echo What is the name of your project?
read proj_name

index_html='
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>'$proj_name'</title>
    <link rel="stylesheet" href="css/style.css" />
    <script defer src="js/script.js"></script>
  </head>

  <body>
    <main>
    </main>
  </body>
</html>
'

style_scss="
@use 'nullstyle' as *;
@use 'variables' as *;
@use 'mixin' as *;

.container {
    max-width: 1200px;
    width: 100%;
    padding: 0 20px;
    margin: 0 auto;
}
"

mixins_scss='
@mixin flex-row-align-centered($justy: start) {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: $justy;
}

@mixin flex-column-align-centered($justy: start) {
  @include flex-row-align-centered($justy);
  flex-direction: column;
}

@mixin wh ($var) {
  width: $var;
  height: $var;
}
'

nullstyle_scss='
/*zeroing default styles*/
*{padding: 0;margin: 0;border: 0;}
*,*:before,*:after{-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;}
:focus,:active{outline: none;}
a:focus,a:active{outline: none;}
nav,footer,header,aside{display: block;}
html,body{height:100%;width:100%;font-size:100%;line-height:1;font-size:14px;-ms-text-size-adjust:100%;-moz-text-size-adjust:100%;-webkit-text-size-adjust:100%;}
input,button,textarea{font-family:inherit;}
input::-ms-clear{display: none;}
button{cursor: pointer;}
button::-moz-focus-inner{padding:0;border:0;}
a,a:visited{text-decoration: none;}
a:hover{text-decoration: none;}
ul li{list-style: none;}
img{vertical-align: top;}
h1,h2,h3,h4,h5,h6{font-size:inherit;font-weight: inherit;}
'

mkdir $proj_name
cd $proj_name

mkdir {img,css,scss,js}
touch index.html
echo $index_html > index.html

touch scss/style.scss
echo $style_scss > scss/style.scss

touch scss/_nullstyle.scss
echo $nullstyle_scss > scss/_nullstyle.scss
touch scss/_variables.scss
touch scss/_mixins.scss
echo $mixins_scss > scss/_mixins.scss

touch js/script.js

echo "Project $proj_name has been created!"

open_code=y
[[ -t 0 ]] &&
read -n 1 -p $'\e[1;33m
Open created project by VS Code? (Y/n)\e[0m ' open_code
if [[ $open_code =~ ^(y|Y|)$ ]]
then
    code .
fi

kill $PPID
